name: 'Chef Cookbook Version compare'
description: 'Checks current version of Chef cookbook with the main branch to verify it has been bumped'
runs:
  using: composite
  steps:
    - run: git show origin/main:metadata.rb > metadata-main.rb
      shell: bash
    - uses: node16
      run: index.js