---
name: cookbook

on:
  workflow_call:
    inputs:
      cookbook_name:
        required: true
        type: string
    
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Run RSpec
        run: chef exec rspec -f j -o tmp/rspec_results.json -f p
        env:
          CHEF_LICENSE: accept-no-persist

  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Run Cookstyle
        run: chef exec cookstyle --display-cop-names --extra-details
        env:
          CHEF_LICENSE: accept-no-persist

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main
  
  kitchen:
    runs-on: [self-hosted, linux, lt]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Test kitchen
        run: kitchen test
      - name: Cleanup Test kitchen
        run: kitchen destroy
        if: always()
  
  deploy:
    runs-on: [self-hosted, linux, lt]
    if: github.ref == 'refs/head/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Clean and install dependencies
        run: |
          rm -rf ~/.berkself
          berks install
      - name: Upload cookbooks to server
        run: |
          knife cookbook upload ${{ inputs.cookbook_name }} -o "../:~/.berkshelf/cookbooks/" --include-dependencies --profile coe-lt-tier1
          knife cookbook upload ${{ inputs.cookbook_name }} -o "../:~/.berkshelf/cookbooks/" --include-dependencies --profile coe-lt-tier2
      - name: Cleanup Berkself
        run: rm -rf ~/.berkself
        if: always()